In [1]:
import pandas as pd

In [4]:
from sklearn.model_selection import train_test_split

df = pd.read_csv("data/conexao-labels-full-4.1nano-p2.csv", sep='|')
print(df.shape)
df.head()

(12287, 3)

,sentence,label,justification
0,E certamente com o risco de ser injusto com al...,Loaded_Language,The sentence uses emotionally charged words li...
1,"Queda de 27,5% em relação ao mesmo período do ...",No_Label,The sentences are factual reports and do not c...
2,"A seguir, são sugeridas algumas medidas de com...",No_Label,The sentence is informational and describes me...
3,Cito onze aqui:\n– PL 6944/2017: impede a limi...,No_Label,"The sentence is informational, listing legisla..."
4,"Um ex-presidente, dos mais populares e populis...",Loaded_Language,The sentence uses emotionally charged words li...

In [5]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

train_df.to_csv("training_data/conexao-labels-train.csv", index=False, sep='|')
test_df.to_csv("training_data/conexao-labels-test.csv", index=False, sep='|')

In [7]:
df = pd.read_csv("data/g1-labels-full-4.1nano-p2.csv")
print(df.shape)
display(df.head())

train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)
train_df.to_csv("training_data/g1-labels-train.csv", index=False, sep='|')
test_df.to_csv("training_data/g1-labels-test.csv", index=False, sep='|')

(3668, 3)

,sentence,label,justification
0,O vídeo foi gravado no cemitério de Annotto Ba...,No_Label,"The sentence is purely informational, describi..."
1,OFato ou Fakepesquisou pelo cemitério de Annot...,No_Label,The sentence provides factual information abou...
2,Mas isso não é verdade.OFato ou Fakeenviou o m...,No_Label,The sentence primarily relays factual informat...
3,"Segundo o ex-ministro do TSE Carlos Horbach, r...",No_Label,The sentence is a detailed explanation of a le...
4,"Não há, no texto do ECA Digital, qualquer menç...",No_Label,The sentence provides an informational clarifi...