## core

In [ ]:
import pandas as pd
from pathlib import Path

In [ ]:
labeled_df = pd.read_csv("datasets/labeled_df.csv")
labeled_df.head()

,labels,justification,text
0,"Xingamento-Rotulação,Apelo_ao_Medo-Preconceito...",O texto utiliza a rotulação ao chamar Lula de ...,carnaval em olinda. arrastão monstro. fazuele ...
1,"Apelo_ao_Medo-Preconceito,Linguagem_Carregada,...",O texto utiliza o medo ao mencionar que há 'ca...,carro alegórico da escola de samba grande rio...
2,"Xingamento-Rotulação,Dúvida,Apelo_ao_Medo-Prec...",O texto menciona 'cantor léo apoiando atos ant...,cantor léo apoiando atos antidemocráticos. alg...
3,"Apelo_ao_Medo-Preconceito,Linguagem_Carregada,...",O texto utiliza apelo ao medo ao descrever a g...,versão 1 ore muito pela cantora anitta! ela es...
4,NaN,O texto apresenta informações factuais sobre a...,morre erasmo carlos aos 81 anos cantor conside...

## limpeza

In [3]:
labeled_df.isnull().sum()

labels           5
justification    0
text             0
dtype: int64

In [4]:
labeled_df.shape

(1791, 3)

In [5]:
print("linhas nulas:")
print(labeled_df[labeled_df['labels'].isnull()])

linhas nulas:
     labels                                      justification  \
4       NaN  O texto apresenta informações factuais sobre a...
269     NaN  ERROR: Expecting ':' delimiter: line 6450 colu...
1237    NaN  O texto é informativo e relata um evento, indi...
1325    NaN  ERROR: Expecting ':' delimiter: line 29269 col...
1397    NaN  O texto é uma simples declaração de fatos e in...

                                                   text
4     morre erasmo carlos aos 81 anos cantor conside...
269   na argentina a realidade não é de picanha, e s...
1237  pink floyd anuncia nova turne, com shows no br...
1325  bolsonaro e o cancer terminal que estaria send...
1397  pib do brasil ultrapassa o do reino unido e pa...

In [6]:
notNull_df = labeled_df[labeled_df['labels'].notnull()]
print(f"\ndf após remover linhas sem rótulos: {notNull_df.shape}")

df após remover linhas sem rótulos: (1786, 3)

In [10]:
notNull_df = notNull_df.rename(columns={'text': 'texto', 'labels': 'rotulo', 'justification': 'argumento'})
df = notNull_df[['texto', 'rotulo', 'argumento']]
df.head()

,texto,rotulo,argumento
0,carnaval em olinda. arrastão monstro. fazuele ...,"Xingamento-Rotulação,Apelo_ao_Medo-Preconceito...",O texto utiliza a rotulação ao chamar Lula de ...
1,carro alegórico da escola de samba grande rio...,"Apelo_ao_Medo-Preconceito,Linguagem_Carregada,...",O texto utiliza o medo ao mencionar que há 'ca...
2,cantor léo apoiando atos antidemocráticos. alg...,"Xingamento-Rotulação,Dúvida,Apelo_ao_Medo-Prec...",O texto menciona 'cantor léo apoiando atos ant...
3,versão 1 ore muito pela cantora anitta! ela es...,"Apelo_ao_Medo-Preconceito,Linguagem_Carregada,...",O texto utiliza apelo ao medo ao descrever a g...
5,globo já gravou o vídeo de fim de ano com lula...,"Linguagem_Carregada,Apelo_ao_Medo-Preconceito,...","O texto utiliza linguagens carregadas, como ""v..."

In [24]:
Path("datasets").mkdir(parents=True, exist_ok=True)
df.to_csv("datasets/base_df.csv", index=False, encoding="utf-8")

print("Arquivo salvo em: datasets/base_df.csv")

Arquivo salvo em: datasets/base_df.csv